version: "3.9"
services:
  database:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=ticketAppPassword77%
    restart: always
    ports:
      - "1433:1433"
    #volumes:
    #  - C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TicketApplicationDB.mdf:/var/opt/mssql/data/master.mdf
    #C:\templatedata\master.mdf:/var/opt/mssql/data/master.mdf
  web_app:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: web_app_application
    ports:
      - "8080:80"
    depends_on:
      - database