version: "3.9"
services:
  database:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=ticketAppPassword77%
    restart: always
    ports:
      - "1433:1433"
  web_app:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: web_app_application
    ports:
      - "8080:80"
    depends_on:
      - database