apiVersion: v1
kind: Service
metadata:
  name: mssql-database-statefulset-service
  namespace: devops-project
spec:
  type: ClusterIP
  selector:
    component: database
  ports:
    - port: 1433
      targetPort: 1433
