name: DevOps_Project Deploy
on:
    push:
        branches:
            - master
env:
    SHA: $(git rev-parse HEAD)
               
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
            - run: docker build -t borjanob/ticket_app:latest -t borjanob/ticket_app:${{ env.SHA }} .
            - run: docker push borjanob/ticket_app:latest
            - run: docker push borjanob/ticket_app:${{ env.SHA }}
